server:
  port: 8082
  
Spring:
    application:
     name: cloud-client2
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/