server:
  port: 8989

logging:
    level:
      root: debug

security:
  basic: false

Spring:
    application:
     name: cloud-turbine

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

turbine:
  aggregator:
    cluster-config: false
  app-config: cloud-client,cloud-hystrix
  cluster-name-expression: new String("default")
