server:
  port: 8088
  
Spring:
    application:
     name: cloud-ribbon
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/