server:
  port: 8802
  
Spring:
  application:
    name: cloud-bus-client
  rabbitmq:
    host: 117.50.1.227
    port: 15672
    username: admin
    password: admin


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/