server:
  port: 8802
  
spring:
  application:
    name: cloud-bus-client
  rabbitmq:
    host: 117.48.231.56
    port: 8892
    username: admin
    password: lulu0424.


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/