mybatis:
  config:
    location: mybatis-config.xml
spring:
  datasource:
    db1:
      jdbcUrl: jdbc:h2:~/test1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    db2:
      jdbcUrl: jdbc:h2:~/test2;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console   # h2 web consloe 路径
      enabled: true       # 开启 h2 web consloe，默认为 false
      settings:
        web-allow-others: true    #允许远程访问 h2 web consloe