server:
  port: 8803

logging:
    level:
      root: info

Spring:
    application:
     name: cloud-stream

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

