server:
  port: 8803

logging:
    level:
      root: info

spring:
  application:
     name: cloud-stream
  rabbitmq:
    host: localhost
    port: 8892
    username: {your username}
    password: {your password}
    virtual-host: /

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

