server:
  port: 8083
  
mybatis: 
  config:
    location: mybatis-config.xml
  
Spring:
    application:
     name: cloud-client
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

