server:
  port: 8099
  
Spring:
    application:
     name: cloud-config
    cloud:
      config:
        server:
          git:
            uri: file:///E:/workspace/IdeaProjects/study-micro-services/study-micro-services/study-micro-services-config/src/main/java/resources

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

