server:
  port: ${appPort:8071}


Spring:
  application:
    name: cloud-dynamic-routes

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/