server:
  port: ${appPort:8071}
#  tomcat:
#    max-threads: 500
#    max-connections: 500

spring:
  application:
    name: cloud-dynamic-routes
  h2:
    console:
      path: /h2-console   # h2 web consloe 路径
      enabled: true       # 开启 h2 web consloe，默认为 false
      settings:
        web-allow-others: true    #允许远程访问 h2 web consloe
  datasource:
    username: sa
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name:  org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql

  cloud:
    refresh:
      refreshable: none
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


mybatis:
  # Eclipse 配置
  #  config:
  #    location: mybatis-config.xml

  # Idea 配置
  config-location: classpath:mybatis-config.xml


zuul:
  host:
    connect-timeout-millis: 6000  # HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 6000   # socket超时

  semaphore:
    max-semaphores: 1000 # could not acquire a semaphore for execution

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


