server:
  port: ${appPort:8071}

# ribbon.eureka.enabled: false
zuul:
  ignoredPatterns: /**/admin/**, /proxyurl
  routes:
    zuulDemo1:
      path: /**
      url: http://localhost/admin/health
      # stripPrefix set to true if context path is set to /
      stripPrefix: true


Spring:
  application:
    name: cloud-ribbon-dynamic-routes

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/