server:
  port: 8801
  
Spring:
  application:
    name: cloud-bus
  rabbitmq:
    host: localhost
    port: 15672
    username: admin
    password: admin


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/