server:
  port: 8888
  
Spring:
    application:
     name: cloud-zuul

zuul:
  routes:
   cloud-ribbon:
    path: /cloud-ribbon/**
    serviceId: cloud-ribbon
   cloud-feign:
    path: /cloud-feign/**
    serviceId: cloud-feign

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/