server:
  port: 8888
  
Spring:
    application:
     name: cloud-zuul

zuul:
  routes:
   eurekaClient:
    path: /cloud-ribbon/**
    serviceId: cloud-ribbon

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/