server:
  port: 8888
  
Spring:
    application:
     name: cloud-ribbon

zuul:
  ignored-services: ignored-service          # 需要忽视的服务(配置后将不会被路由)
  routes:
   cloud-ribbon:
    path: /cloud-ribbon/**
    serviceId: cloud-ribbon
   cloud-feign:
    path: /cloud-feign/**
    serviceId: cloud-feign

   cloud-client5:
    path: /cloud-client5/**
    serviceId: cloud-client5
   cloud-client6:
    path: /cloud-client6/**
    url: http://localhost:8006/ # 也可以指定为url

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/