server:
  port: 8888
  
Spring:
    application:
     name: cloud-zuul

zuul:
  routes:
   cloud-ribbon:
    path: /cloud-ribbon/**
    serviceId: cloud-ribbon
   cloud-feign:
    path: /cloud-feign/**
    serviceId: cloud-feign

   cloud-client5:
    path: /cloud-client5/**
    serviceId: cloud-client5
   cloud-client6:
    path: /cloud-client6/**
    serviceId: cloud-client6

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/