server:
  port: 8909
  
Spring:
    application:
     name: cloud-config-client
    cloud:
      config:
        server:
          git:
            uri: https://github.com/bage2014/study-micro-services/
            search-paths: /**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

